package sieve

import (
	"strings"
	"testing"

	"mailhearth/internal/model"
)

func TestCompileRules(t *testing.T) {
	rules := []model.SieveRule{
		{
			ID: "r1", Name: "Newsletters", Enabled: true, Match: "any",
			Conditions: []model.SieveCondition{
				{Field: "from", Op: "contains", Value: "newsletter@"},
				{Field: "header", Header: "List-Unsubscribe", Op: "matches", Value: "*"},
			},
			Actions: []model.SieveAction{{Type: "move", Folder: "Newsletters"}, {Type: "markread"}, {Type: "stop"}},
		},
		{
			ID: "r2", Name: "Boss", Enabled: true, Match: "all",
			Conditions: []model.SieveCondition{{Field: "from", Op: "is", Value: "boss@acme.test"}, {Field: "size", Op: "over", Value: "2M"}},
			Actions:    []model.SieveAction{{Type: "flag"}, {Type: "forward", Address: "me@example.com"}},
		},
		{ID: "r3", Name: "Old rule", Enabled: false, Conditions: []model.SieveCondition{{Field: "subject", Value: "x"}}, Actions: []model.SieveAction{{Type: "discard"}}},
		{
			ID: "r4", Name: "Spam words", Enabled: true,
			Conditions: []model.SieveCondition{{Field: "body", Op: "not_contains", Value: `say "hi"`}},
			Actions:    []model.SieveAction{{Type: "copy", Folder: "Archive"}},
		},
	}
	script, err := Compile(rules, &model.Vacation{Enabled: true, Subject: "Out of office", Body: "I am away.\n.until Monday", Days: 3})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`require ["fileinto", "imap4flags", "copy", "body", "vacation"];`,
		`vacation :days 3 :subject "Out of office" text:`,
		"I am away.\r\n..until Monday\r\n.\r\n",
		`if anyof (address :contains "from" "newsletter@",`,
		`header :matches "List-Unsubscribe" "*")`,
		`fileinto "Newsletters";`,
		`addflag "\\Seen";`,
		`if allof (address :is "from" "boss@acme.test",`,
		`size :over 2M)`,
		`addflag "\\Flagged";`,
		`redirect :copy "me@example.com";`,
		`# (disabled) Old rule`,
		`if not body :text :contains "say \"hi\"" {`,
		`fileinto :copy "Archive";`,
	} {
		if !strings.Contains(script, want) {
			t.Errorf("script missing %q\n%s", want, script)
		}
	}
	if strings.Contains(script, "discard") {
		t.Error("disabled rule must not be compiled")
	}
}

func TestCompileValidation(t *testing.T) {
	cases := []model.SieveRule{
		{Name: "no conditions", Enabled: true, Actions: []model.SieveAction{{Type: "stop"}}},
		{Name: "no actions", Enabled: true, Conditions: []model.SieveCondition{{Field: "subject", Value: "x"}}},
		{Name: "bad header", Enabled: true, Conditions: []model.SieveCondition{{Field: "header", Header: "X Y", Value: "x"}}, Actions: []model.SieveAction{{Type: "stop"}}},
		{Name: "bad size", Enabled: true, Conditions: []model.SieveCondition{{Field: "size", Op: "over", Value: "lots"}}, Actions: []model.SieveAction{{Type: "stop"}}},
		{Name: "bad addr", Enabled: true, Conditions: []model.SieveCondition{{Field: "subject", Value: "x"}}, Actions: []model.SieveAction{{Type: "forward", Address: "nope"}}},
		{Name: "bad folder", Enabled: true, Conditions: []model.SieveCondition{{Field: "subject", Value: "x"}}, Actions: []model.SieveAction{{Type: "move"}}},
		{Name: "bad op", Enabled: true, Conditions: []model.SieveCondition{{Field: "subject", Op: "regex", Value: "x"}}, Actions: []model.SieveAction{{Type: "stop"}}},
	}
	for _, r := range cases {
		if _, err := Compile([]model.SieveRule{r}, nil); err == nil {
			t.Errorf("expected error for %q", r.Name)
		}
	}
	if _, err := Compile(nil, &model.Vacation{Enabled: true}); err == nil {
		t.Error("vacation without body must fail")
	}
	script, err := Compile(nil, nil)
	if err != nil || !strings.HasPrefix(script, "# Generated by Mailhearth") {
		t.Fatalf("empty script: %v %q", err, script)
	}
}
